name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test

  build_ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    container:
      image: swift:5.4.2-focal
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test